import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Navbar from "@/components/shared/Navigation";
import { ThemeProvider } from "@/context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "iHabits",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      signUpUrl="/sign-up"
      signInUrl="/sign-in"
      afterSignInUrl="/dashboard"
      afterSignUpUrl="/dashboard"
      key={process.env.CLERK_SECRET_KEY}
      appearance={{
        elements: {
          formButtonPrimary: "dark:bg-dark-500",
          footerActionLink: `primary-text-gradient hover:text-primary-500`,
        },
      }}
    >
      <html lang="en">
        <ThemeProvider>
          <body className={inter.className}>
            <main>
              {" "}
              <Navbar />
              <div className="flex">
                <LeftSidebar />
                <section className="flex min-h-screen flex-1 flex-col px-6 pb-6 pt-36 max-md:pb-14 sm:px-14">
                  <div className="mx-auto w-full max-w-5xl">{children}</div>
                </section>
              </div>
            </main>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>
  );
}
